variables:
  SolutionBaseName: 'DFC.Composite.Shell.Moc.OneCol'
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

steps:
 - task: gittools.gitversion.gitversion-task.GitVersion@4
   displayName: GitVersion
   inputs:
     preferBundledVersion: false
 
 - task: DotNetCoreCLI@2
   displayName: 'dotnet build'
   inputs:
     command: 'build'

     # test and publish

 - task: UseDotNet@2
   displayName: 'Use .NET Core sdk'
   inputs:
     packageType: sdk
     version: 2.2.x
     installationPath: $(Agent.ToolsDirectory)/dotnet

 - task: DotNetCoreCLI@2
   displayName: dotnet test
   inputs:
    command: test
    projects: '**/*.csproj'
    configuration: ${{ variables.buildConfiguration }}
 - task: DotNetCoreCLI@2
   displayName: dotnet publish
   inputs:
    command: publish
    projects: 'DFC.Composite.Shell.Moc.OneCol\DFC.Composite.Shell.Moc.OneCol.csproj'
    configuration: ${{ variables.buildConfiguration }}
    arguments: '--output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
    publishWebProjects: false

 - task: CopyFiles@2
   displayName: 'Copy Files to: $(build.artifactstagingdirectory)/Azure'
   inputs:
     sourceFolder: 'Resources'
     contents: '**'
     targetFolder: '$(build.artifactstagingdirectory)/Azure'
 - task: PublishBuildArtifacts@1
   displayName: 'Publish Artifact: ${{ variables.SolutionBaseName }}'
   inputs:
     pathtoPublish: $(build.artifactstagingdirectory)
     artifactName: ${{ variables.SolutionBaseName }}
     publishLocation: container
